import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import Cabecalho from '@/components/Cabecalho/Cabecalho'
import Rodape from '@/components/Rodape/Rodape'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">


      <body className={inter.className}>
        {/* <div>
          <p><Link href="/produtos/calca">CALÇA</Link></p>
          <p><Link href="/produtos/camisa">CAMISA</Link></p>
          <p><Link href="/produtos/meia">MEIA</Link></p>
          <p><Link href="/produtos/tenis">TÊNIS</Link></p>
        </div> */}
        <Cabecalho />


        {children}
        
        <Rodape />
        {/* <p>RODAPÉ</p> */}
      </body>
    </html>
  )
}
